build: format yaml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,10 +36,9 @@ jobs:
                   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
               run: npx semantic-release
     no-release:
-      if: ${{ (github.event_name != 'pull_request') && (github.event.workflow_run.conclusion == 'failure') }}
-      name: No Release
-      runs-on: ubuntu-latest
-      steps:
-        - name: CI Failure
-          run: echo "CI Failure" && exit 1
-
+        if: ${{ (github.event_name != 'pull_request') && (github.event.workflow_run.conclusion == 'failure') }}
+        name: No Release
+        runs-on: ubuntu-latest
+        steps:
+            - name: CI Failure
+              run: echo "CI Failure" && exit 1
